#!/usr/bin/env python3

"""Ryu OpenFlow 1.3 enterprise zone firewall controller.

Zero Trust policy is enforced with explicit source/destination MAC pairs.
"""

from ryu.base import app_manager
from ryu.controller import ofp_event
from ryu.controller.handler import CONFIG_DISPATCHER, MAIN_DISPATCHER, set_ev_cls
from ryu.lib.packet import ether_types
from ryu.lib.packet import ethernet
from ryu.lib.packet import packet
from ryu.ofproto import ofproto_v1_3


class ZoneController(app_manager.RyuApp):
    OFP_VERSIONS = [ofproto_v1_3.OFP_VERSION]

    def __init__(self, *args, **kwargs):
        super(ZoneController, self).__init__(*args, **kwargs)
        self.mac_to_port = {}

        # Explicit endpoint MACs.
        self.h1 = "00:00:00:01:00:00"  # User1
        self.h2 = "00:00:00:02:00:00"  # User2
        self.h3 = "00:00:00:03:00:00"  # App1
        self.h4 = "00:00:00:04:00:00"  # App2
        self.h5 = "00:00:00:05:00:00"  # Database
        self.h6 = "00:00:00:06:00:00"  # DMZ Web
        self.h7 = "00:00:00:07:00:00"  # DMZ Mail
        self.h8 = "00:00:00:08:00:00"  # DMZ VPN

        self.known_hosts = {
            self.h1,
            self.h2,
            self.h3,
            self.h4,
            self.h5,
            self.h6,
            self.h7,
            self.h8,
        }

        # Explicit allow matrix (directional tuples).
        self.allowed_pairs = {
            # Users <-> Apps
            (self.h1, self.h3),
            (self.h1, self.h4),
            (self.h2, self.h3),
            (self.h2, self.h4),
            (self.h3, self.h1),
            (self.h3, self.h2),
            (self.h4, self.h1),
            (self.h4, self.h2),

            # Apps <-> DB (reverse allowed for return traffic in stateless pipeline)
            (self.h3, self.h5),
            (self.h4, self.h5),
            (self.h5, self.h3),
            (self.h5, self.h4),

            # DMZ <-> Apps
            (self.h6, self.h3),
            (self.h6, self.h4),
            (self.h7, self.h3),
            (self.h7, self.h4),
            (self.h8, self.h3),
            (self.h8, self.h4),
            (self.h3, self.h6),
            (self.h3, self.h7),
            (self.h3, self.h8),
            (self.h4, self.h6),
            (self.h4, self.h7),
            (self.h4, self.h8),
        }

    def add_flow(self, datapath, priority, match, actions, idle_timeout=300, hard_timeout=0):
        """Install OpenFlow rule; empty actions means DROP."""
        parser = datapath.ofproto_parser
        ofproto = datapath.ofproto

        instructions = []
        if actions:
            instructions = [parser.OFPInstructionActions(ofproto.OFPIT_APPLY_ACTIONS, actions)]

        mod = parser.OFPFlowMod(
            datapath=datapath,
            priority=priority,
            match=match,
            instructions=instructions,
            idle_timeout=idle_timeout,
            hard_timeout=hard_timeout,
        )
        datapath.send_msg(mod)

    @set_ev_cls(ofp_event.EventOFPSwitchFeatures, CONFIG_DISPATCHER)
    def switch_features_handler(self, ev):
        datapath = ev.msg.datapath
        parser = datapath.ofproto_parser
        ofproto = datapath.ofproto

        # Reset switch state so policy starts from a known baseline.
        delete_all = parser.OFPFlowMod(
            datapath=datapath,
            command=ofproto.OFPFC_DELETE,
            out_port=ofproto.OFPP_ANY,
            out_group=ofproto.OFPG_ANY,
            priority=0,
            match=parser.OFPMatch(),
        )
        datapath.send_msg(delete_all)

        # Table-miss => controller for first-packet policy decision.
        miss_match = parser.OFPMatch()
        miss_actions = [parser.OFPActionOutput(ofproto.OFPP_CONTROLLER, ofproto.OFPCML_NO_BUFFER)]
        self.add_flow(datapath, priority=0, match=miss_match, actions=miss_actions, idle_timeout=0)

        # ARP is always flooded for reliable endpoint discovery.
        arp_match = parser.OFPMatch(eth_type=ether_types.ETH_TYPE_ARP)
        arp_actions = [parser.OFPActionOutput(ofproto.OFPP_FLOOD)]
        self.add_flow(datapath, priority=250, match=arp_match, actions=arp_actions, idle_timeout=0)

    @set_ev_cls(ofp_event.EventOFPPacketIn, MAIN_DISPATCHER)
    def packet_in_handler(self, ev):
        msg = ev.msg
        datapath = msg.datapath
        parser = datapath.ofproto_parser
        ofproto = datapath.ofproto
        dpid = datapath.id

        try:
            in_port = msg.match["in_port"]
            self.mac_to_port.setdefault(dpid, {})

            pkt = packet.Packet(msg.data)
            eth = pkt.get_protocol(ethernet.ethernet)
            if eth is None:
                return

            # Ignore LLDP generated by the control plane.
            if eth.ethertype == ether_types.ETH_TYPE_LLDP:
                return

            src = eth.src
            dst = eth.dst
            self.mac_to_port[dpid][src] = in_port

            # ARP bypass: permit neighborhood resolution.
            if eth.ethertype == ether_types.ETH_TYPE_ARP:
                self._packet_out(datapath, msg, in_port, [parser.OFPActionOutput(ofproto.OFPP_FLOOD)])
                return

            # Preserve non-IPv4 fast-path (e.g., IPv6 discovery noise).
            if eth.ethertype != ether_types.ETH_TYPE_IP:
                self._packet_out(datapath, msg, in_port, [parser.OFPActionOutput(ofproto.OFPP_FLOOD)])
                return

            pair = (src, dst)

            # Apply Zero Trust policy only to known enterprise endpoints.
            if src in self.known_hosts and dst in self.known_hosts:
                if pair not in self.allowed_pairs:
                    drop_match = parser.OFPMatch(
                        eth_type=ether_types.ETH_TYPE_IP,
                        eth_src=src,
                        eth_dst=dst,
                    )
                    self.add_flow(datapath, priority=200, match=drop_match, actions=[], idle_timeout=600)
                    self.logger.info("* SECURITY BLOCK: %s->%s *", src, dst)
                    return

            # Allowed or out-of-scope traffic: switch learning behavior.
            if dst in self.mac_to_port[dpid]:
                out_port = self.mac_to_port[dpid][dst]
            else:
                out_port = ofproto.OFPP_FLOOD

            actions = [parser.OFPActionOutput(out_port)]

            # Install forwarding flow for known destination paths.
            if out_port != ofproto.OFPP_FLOOD:
                allow_match = parser.OFPMatch(
                    in_port=in_port,
                    eth_type=ether_types.ETH_TYPE_IP,
                    eth_src=src,
                    eth_dst=dst,
                )
                self.add_flow(datapath, priority=100, match=allow_match, actions=actions, idle_timeout=300)

            self._packet_out(datapath, msg, in_port, actions)

        except Exception as exc:  # Defensive: keep controller alive on malformed frames.
            self.logger.exception("PacketIn processing error: %s", exc)

    def _packet_out(self, datapath, msg, in_port, actions):
        """Send immediate forwarding decision for current packet."""
        data = None
        if msg.buffer_id == datapath.ofproto.OFP_NO_BUFFER:
            data = msg.data

        out = datapath.ofproto_parser.OFPPacketOut(
            datapath=datapath,
            buffer_id=msg.buffer_id,
            in_port=in_port,
            actions=actions,
            data=data,
        )
        datapath.send_msg(out)


